# fr.toml - v10.0.198.2
[addon]
appDesc = '''Télécharger des vidéos depuis Internet'''
restore_purchase_button = '''Restaurer votre achat'''
get_premium_button = '''Devenez Premium'''
back = '''Retour'''
waiting_for_media = '''En attente de média...'''
nomedia_title = '''Vous ne trouvez pas ce que vous cherchez ?'''
nomedia_description = '''Démarrez la vidéo (et passez les publicités si nécessaire) pour aider à détecter le contenu. Ou signalez nous un contenu manquant.'''
nomedia_reload_button = '''Forcer la détection'''
nomedia_reload_button_tooltip = '''Force le rechargement de la page (efface les cookies)'''
show_nomedia_button = '''Pas de vidéo?'''
show_nomedia_button_tooltip = '''Cliquez ici si vous ne voyez pas votre vidéo'''
setting_button_tooltip = '''Paramètres'''
history_button_tooltip = '''Afficher l'historique de téléchargements '''
show_all_history_button = '''Tout montrer'''
complete_title = '''Téléchargement(s) terminé(s)'''
hide_complete_button = '''cacher'''
translate_button_tooltip = '''Aidez à traduire VDH'''
open_source_tab_button_tooltip = '''Ouvrir l'onglet d'origine'''
retry_download_button_tooltip = '''Réessayer le téléchargement'''
delete_file_button_tooltip = '''Supprimer le fichier'''
download_directory_button_tooltip = '''Montrer le dossier de téléchargement'''
clear_downloaded_tooltip = '''Vider l'historique de téléchargement'''
show_in_popup_button_tooltip = '''Afficher dans un popup'''
show_in_sidebar_button_tooltip = '''Afficher dans une barre latérale'''
video_not_playing_button_tooltip = '''La vidéo ne se lance pas ?'''
play = '''Jouer'''
warn_drm_tooltip = '''DRM détectés'''
version_title = '''Version'''
account_title = '''Compte'''
one_hundred_downloads_title = '''Vous avez téléchargé 100 vidéos !'''
leave_review_description = '''Nous espérons que vous appréciez Video DownloadHelper :) Voudriez-vous laisser un gentil commentaire sur le site de l'addon ?'''
leave_review_button = '''Laisser un commentaire'''
account_status = '''Statut'''
account_status_premium = '''Premium ($1)'''
free_account = '''Plan gratuit'''
copy_to_clipboard = '''Copier'''
my_account_button = '''Mon compte'''
download_title = '''Téléchargements'''
show_notification = '''Afficher les notifications de fin de téléchargement'''
max_parallel_downloads = '''Téléchargements simultanés maximum '''
change_download_directory = '''Changer le répertoire de téléchargement'''
saveas_detected_warning = '''Nous avons détecté que votre navigateur affiche une boîte de dialogue « Enregistrer sous » une fois le téléchargement terminé. Nous vous recommandons de désactiver cette option dans les paramètres de votre navigateur.'''
change_saveas_setting = '''Changer le paramètre'''
private_browsing_title = '''Navigation privée'''
private_browsing_warning = '''Video DownloadHelper n'est pas activé en mode navigation privée. Vous devez activer cette option à la main. (ceci n'est pas obligatoire)'''
private_browsing_notifications = '''Afficher une notification même en navigation privée'''
private_browsing_button = '''Changer le paramètre de navigation privée'''
prefer_original_audio = '''Audio original préféré'''
prefer_hls = '''HLS préféré'''
settings_history_title = '''Historique'''
transient_history_description = '''Afficher les téléchargements finis dans la fenêtre'''
history_limit = '''Supprimer l'historique après X jours'''
appearance_title = '''Apparence'''
theme_title = '''Thème '''
theme_light = '''Clair'''
theme_dark = '''Sombre'''
theme_system = '''Système'''
popup_size_title = '''Taille de la fenêtre'''
popup_size_small = '''Petite'''
popup_size_medium = '''Moyenne'''
popup_size_big = '''Grande'''
panel_position_title = '''Position de la fenêtre'''
use_popup = '''Afficher dans un popup'''
use_sidebar = '''Afficher dans une barre latérale'''
behavior_title = '''Comportement'''
show_in_context_menu = '''Accéder aux commandes via un clic droit dans la page'''
restart_addon = '''Recharger l'addon'''
reset_settings = '''Réinitialiser les paramètres'''
prefer_highest_quality = '''Sélectionner la qualité la plus élevée disponible au lieu du 1080p par défaut (téléchargement plus lent mais de meilleure qualité).'''
preview_mode_title = '''Aperçu du média'''
preview_mode_none = '''Désactivé'''
preview_mode_video = '''Aperçu vidéo court'''
preview_mode_image = '''Image'''
history_title = '''Historique des téléchargements'''
history_warning = '''Nous ne sauvegardons pas votre historique de téléchargements. Voulez-vous que DownloadHelper conserve votre historique de téléchargements ?'''
history_warning_2 = '''Pas d'inquiétudes, tout reste stocké sur votre appareil. Votre vie privée est importante pour nous.'''
enable_history = '''Activer l'historique'''
clear_history = '''Effacer l'historique'''
disable_history = '''Désactiver l'historique'''
no_downloads_yet = '''Pas encore d'entrées.'''
download_failed = '''Le téléchargement a échoué'''
download_failed_description = '''Ce média n'a malheureusement pas pu être téléchargé. Nous essayons de supporter autant de sites que possible, donc n'hésitez pas à faire un rapport d'erreur !'''
download_interrupted = '''Téléchargement interrompu'''
download_interrupted_description = '''Nous avons réussi à télécharger votre fichier, mais un problème de réseau est survenu, il se peut donc que le fichier soit plus court que prévu. Nous essayons de prendre en charge le plus grand nombre de sites possible, donc votre aide nous serait précieuse si vous pouviez signaler ce problème (c’est anonyme !)'''
download_with_drm_failed_description = '''Quelque chose n’a pas fonctionné. Et nous pensons que cette vidéo est protégée par un DRM. Nous ne prenons pas en charge les vidéos avec DRM.'''
no_youtube = '''Les téléchargements  Youtube ne sont pas autorisés'''
no_youtube_description = '''Malheureusement, le Web Store Chrome n'autorisant pas d'extensions qui téléchargent des vidéos YouTube, nous n'avons pas pu intégrer cette fonctionnalité dans la version Chrome de l'extension.'''
premium_required = '''Statut Premium nécessaire'''
premium_yt_required_description = '''Sans statut Premium, un téléchargement YouTube ne peut être effectué que 2 heures après le précédent.'''
premium_required_description = '''Sans le statut Premium, un téléchargement HLS ne peut être effectué que 2heures  après le précédent'''
youtube_too_many_downloads = '''Oups, Youtube ne semble pas autorisé'''
youtube_too_many_downloads_description = '''YouTube limite parfois le nombre de vidéos pouvant être demandées. Malheureusement, nous n’y pouvons rien. Réessayez plus tard.'''
stop = '''Stop'''
cancel = '''Annuler'''
copy_url = '''Copier l'URL'''
always_copy_url = '''Toujours copier l'URL'''
download_button = '''Télécharger'''
download_as_button_and_menu = '''Télécharger sous…'''
rename_short = '''Renommer'''
always_download_as_menu = '''Toujours télécharger sous...'''
download_audio_button = '''Audio'''
download_audio_and_video_menu = '''Télécharger audio & video'''
download_audio_only_menu = '''Télécharger l'audio'''
audio_only_for_this_website = '''Toujours télécharger uniquement l'audio pour ce site'''
details = '''Détails'''
more_settings = '''Plus de paramètres'''
report = '''Signaler'''
reporting = '''Signalement en cours…'''
reported = '''Signalé, merci !'''
not_playing_title = '''La vidéo ne se lance pas correctement?'''
not_playing_broken_title = '''L'audio ou la vidéo est invalide ?'''
not_playing_broken_description = '''Signalez le contenu défaillant. Nous ferons de notre mieux pour comprendre pourquoi cela a échoué (l’URL de la vidéo est envoyée de manière anonyme — nous ne vous traquons pas !).'''
not_playing_broken_solution_title = '''Essayer un lecteur multimédia moderne'''
not_playing_broken_solution_windows_1 = '''Nous recommandons VLC:'''
not_playing_broken_solution_mac_1 = '''Nous recommandons IINA:'''
not_playing_broken_solution_2 = '''C'est un lecteur moderne, sécurisé et Open Source.'''
not_playing_default_player = '''Assurez-vous que votre lecteur vidéo est défini comme lecteur vidéo par défaut du système.'''
not_playing_default_player_solution_windows = '''Dans le « Panneau de configuration » de Windows, cliquez sur « Programmes par défaut », puis modifiez les programmes par défaut pour votre lecteur.'''
not_playing_default_player_solution_mac = '''Ouvrez le répertoire de téléchargement, faites un clic droit sur le fichier vidéo. Cliquez sur « Lire les informations ». Dans la section « Ouvrir avec », sélectionnez IINA. Cliquez ensuite sur le bouton « Tout modifier ».'''

[web]
back = '''Retour'''
header_help = '''Aide'''
header_community = '''Communauté'''
activate_title = '''Activation'''
activate_pending = '''Patientez…'''
activate_success = '''Validé'''
activate_error = '''Erreur'''
activate_no_addon_found = '''Est-ce que l'addon est installé? Nous ne le trouvons pas.'''
activate_no_method_found = '''Pas de méthode trouvée.'''
activate_help_me = '''J'ai besoin d'aide.'''
issue_title = '''Réactiver votre achat'''
issue_submit = '''Envoyer'''
issue_thank_you = '''Merci'''
issue_enter_email = '''Pour réactiver votre achat, saisissez l'email que vous avez utilisé pour votre achat :'''
issue_email_sent = '''Nous vous avons envoyé un email avec un lien pour ré-activer votre achat.'''
issue_or_digit = '''Ou, vous pouvez aussi saisir le code à 6 chiffres que vous avez reçu :'''
issue_just_digit = '''Saisir le code à 6 chiffres :'''
issue_i_have_a_code = '''(Cliquez ici si vous avez déjà un code)'''
issue_i_have_a_key = '''(Cliquez ici si vous avez déjà une clé de licence)'''
issue_key = '''Entrez votre clé de licence Video DownloadHelper :'''
landing_text1 = '''Téléchargez n'importe quelle vidéo sur internet, facile, ça marche!'''
landing_text2 = '''Plus de 1000+ sites supportés'''
landing_text3 = '''Utilisé par plus de 7 millions d'utilisateurs'''
landing_text4 = '''4.5 étoiles sur les boutique d’extensions'''
landing_install_for_google = '''Installer pour Chrome'''
landing_install_for_mozilla = '''Installer pour Firefox'''
landing_install_for_microsoft = '''Installer pour Edge'''
landing_feature1_title = '''Téléchargement en HD à pleine vitesse'''
landing_feature1_description = '''Les videos sont téléchargées en haute définition, à vitesse maximum. Nous sommes fiers d'être l'outil de téléchargement le plus rapide.'''
landing_feature2_title = '''Archiver vos videos'''
landing_feature2_description = '''Archiver vos vidéos préférées, ne perdez plus vos médias.'''
landing_feature3_title = '''Support de contenu en direct'''
landing_feature3_description = '''Visualiser les contenus en direct hors-ligne, plus besoin d'être présent constamment.'''
landing_feature4_title = '''Téléchargement audio'''
landing_feature4_description = '''Convertissez n'importe quel flux vidéo en contenu audio, en MP3 ou podcasts.'''
premium_hero1 = '''Payez une fois, utilisez pour toujours'''
premium_hero2 = '''Obtenez une licence à vie pour Video DownloadHelper'''
premium_hero3 = '''Téléchargez n'importe quelle vidéo, sans limite.'''
welcome_text = '''Votre extension est prête !'''
welcome_pin_message = '''Épinglez l'icone dans votre barre d'outils :'''
